# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/theguppyfish/lab1OS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/theguppyfish/lab1OS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/theguppyfish/lab1OS/CMakeFiles /home/theguppyfish/lab1OS//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/theguppyfish/lab1OS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Main

# Build rule for target.
Main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Main
.PHONY : Main

# fast build rule for target.
Main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/build
.PHONY : Main/fast

#=============================================================================
# Target rules for targets named factorize

# Build rule for target.
factorize: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 factorize
.PHONY : factorize

# fast build rule for target.
factorize/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/factorize.dir/build.make CMakeFiles/factorize.dir/build
.PHONY : factorize/fast

#=============================================================================
# Target rules for targets named emasearch

# Build rule for target.
emasearch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 emasearch
.PHONY : emasearch

# fast build rule for target.
emasearch/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/emasearch.dir/build.make CMakeFiles/emasearch.dir/build
.PHONY : emasearch/fast

#=============================================================================
# Target rules for targets named combined

# Build rule for target.
combined: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 combined
.PHONY : combined

# fast build rule for target.
combined/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/combined.dir/build.make CMakeFiles/combined.dir/build
.PHONY : combined/fast

src/Bench/EmaSearchStrBenchmark.o: src/Bench/EmaSearchStrBenchmark.cpp.o
.PHONY : src/Bench/EmaSearchStrBenchmark.o

# target to build an object file
src/Bench/EmaSearchStrBenchmark.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/emasearch.dir/build.make CMakeFiles/emasearch.dir/src/Bench/EmaSearchStrBenchmark.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/combined.dir/build.make CMakeFiles/combined.dir/src/Bench/EmaSearchStrBenchmark.cpp.o
.PHONY : src/Bench/EmaSearchStrBenchmark.cpp.o

src/Bench/EmaSearchStrBenchmark.i: src/Bench/EmaSearchStrBenchmark.cpp.i
.PHONY : src/Bench/EmaSearchStrBenchmark.i

# target to preprocess a source file
src/Bench/EmaSearchStrBenchmark.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/emasearch.dir/build.make CMakeFiles/emasearch.dir/src/Bench/EmaSearchStrBenchmark.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/combined.dir/build.make CMakeFiles/combined.dir/src/Bench/EmaSearchStrBenchmark.cpp.i
.PHONY : src/Bench/EmaSearchStrBenchmark.cpp.i

src/Bench/EmaSearchStrBenchmark.s: src/Bench/EmaSearchStrBenchmark.cpp.s
.PHONY : src/Bench/EmaSearchStrBenchmark.s

# target to generate assembly for a file
src/Bench/EmaSearchStrBenchmark.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/emasearch.dir/build.make CMakeFiles/emasearch.dir/src/Bench/EmaSearchStrBenchmark.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/combined.dir/build.make CMakeFiles/combined.dir/src/Bench/EmaSearchStrBenchmark.cpp.s
.PHONY : src/Bench/EmaSearchStrBenchmark.cpp.s

src/Bench/FactorizeBenchmark.o: src/Bench/FactorizeBenchmark.cpp.o
.PHONY : src/Bench/FactorizeBenchmark.o

# target to build an object file
src/Bench/FactorizeBenchmark.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/factorize.dir/build.make CMakeFiles/factorize.dir/src/Bench/FactorizeBenchmark.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/combined.dir/build.make CMakeFiles/combined.dir/src/Bench/FactorizeBenchmark.cpp.o
.PHONY : src/Bench/FactorizeBenchmark.cpp.o

src/Bench/FactorizeBenchmark.i: src/Bench/FactorizeBenchmark.cpp.i
.PHONY : src/Bench/FactorizeBenchmark.i

# target to preprocess a source file
src/Bench/FactorizeBenchmark.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/factorize.dir/build.make CMakeFiles/factorize.dir/src/Bench/FactorizeBenchmark.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/combined.dir/build.make CMakeFiles/combined.dir/src/Bench/FactorizeBenchmark.cpp.i
.PHONY : src/Bench/FactorizeBenchmark.cpp.i

src/Bench/FactorizeBenchmark.s: src/Bench/FactorizeBenchmark.cpp.s
.PHONY : src/Bench/FactorizeBenchmark.s

# target to generate assembly for a file
src/Bench/FactorizeBenchmark.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/factorize.dir/build.make CMakeFiles/factorize.dir/src/Bench/FactorizeBenchmark.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/combined.dir/build.make CMakeFiles/combined.dir/src/Bench/FactorizeBenchmark.cpp.s
.PHONY : src/Bench/FactorizeBenchmark.cpp.s

src/Bench/combined.o: src/Bench/combined.cpp.o
.PHONY : src/Bench/combined.o

# target to build an object file
src/Bench/combined.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/combined.dir/build.make CMakeFiles/combined.dir/src/Bench/combined.cpp.o
.PHONY : src/Bench/combined.cpp.o

src/Bench/combined.i: src/Bench/combined.cpp.i
.PHONY : src/Bench/combined.i

# target to preprocess a source file
src/Bench/combined.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/combined.dir/build.make CMakeFiles/combined.dir/src/Bench/combined.cpp.i
.PHONY : src/Bench/combined.cpp.i

src/Bench/combined.s: src/Bench/combined.cpp.s
.PHONY : src/Bench/combined.s

# target to generate assembly for a file
src/Bench/combined.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/combined.dir/build.make CMakeFiles/combined.dir/src/Bench/combined.cpp.s
.PHONY : src/Bench/combined.cpp.s

src/Bench/emasearch.o: src/Bench/emasearch.cpp.o
.PHONY : src/Bench/emasearch.o

# target to build an object file
src/Bench/emasearch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/emasearch.dir/build.make CMakeFiles/emasearch.dir/src/Bench/emasearch.cpp.o
.PHONY : src/Bench/emasearch.cpp.o

src/Bench/emasearch.i: src/Bench/emasearch.cpp.i
.PHONY : src/Bench/emasearch.i

# target to preprocess a source file
src/Bench/emasearch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/emasearch.dir/build.make CMakeFiles/emasearch.dir/src/Bench/emasearch.cpp.i
.PHONY : src/Bench/emasearch.cpp.i

src/Bench/emasearch.s: src/Bench/emasearch.cpp.s
.PHONY : src/Bench/emasearch.s

# target to generate assembly for a file
src/Bench/emasearch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/emasearch.dir/build.make CMakeFiles/emasearch.dir/src/Bench/emasearch.cpp.s
.PHONY : src/Bench/emasearch.cpp.s

src/Bench/factorize.o: src/Bench/factorize.cpp.o
.PHONY : src/Bench/factorize.o

# target to build an object file
src/Bench/factorize.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/factorize.dir/build.make CMakeFiles/factorize.dir/src/Bench/factorize.cpp.o
.PHONY : src/Bench/factorize.cpp.o

src/Bench/factorize.i: src/Bench/factorize.cpp.i
.PHONY : src/Bench/factorize.i

# target to preprocess a source file
src/Bench/factorize.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/factorize.dir/build.make CMakeFiles/factorize.dir/src/Bench/factorize.cpp.i
.PHONY : src/Bench/factorize.cpp.i

src/Bench/factorize.s: src/Bench/factorize.cpp.s
.PHONY : src/Bench/factorize.s

# target to generate assembly for a file
src/Bench/factorize.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/factorize.dir/build.make CMakeFiles/factorize.dir/src/Bench/factorize.cpp.s
.PHONY : src/Bench/factorize.cpp.s

src/Commands/CdCommand.o: src/Commands/CdCommand.cpp.o
.PHONY : src/Commands/CdCommand.o

# target to build an object file
src/Commands/CdCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Commands/CdCommand.cpp.o
.PHONY : src/Commands/CdCommand.cpp.o

src/Commands/CdCommand.i: src/Commands/CdCommand.cpp.i
.PHONY : src/Commands/CdCommand.i

# target to preprocess a source file
src/Commands/CdCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Commands/CdCommand.cpp.i
.PHONY : src/Commands/CdCommand.cpp.i

src/Commands/CdCommand.s: src/Commands/CdCommand.cpp.s
.PHONY : src/Commands/CdCommand.s

# target to generate assembly for a file
src/Commands/CdCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Commands/CdCommand.cpp.s
.PHONY : src/Commands/CdCommand.cpp.s

src/Commands/ClearCommand.o: src/Commands/ClearCommand.cpp.o
.PHONY : src/Commands/ClearCommand.o

# target to build an object file
src/Commands/ClearCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Commands/ClearCommand.cpp.o
.PHONY : src/Commands/ClearCommand.cpp.o

src/Commands/ClearCommand.i: src/Commands/ClearCommand.cpp.i
.PHONY : src/Commands/ClearCommand.i

# target to preprocess a source file
src/Commands/ClearCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Commands/ClearCommand.cpp.i
.PHONY : src/Commands/ClearCommand.cpp.i

src/Commands/ClearCommand.s: src/Commands/ClearCommand.cpp.s
.PHONY : src/Commands/ClearCommand.s

# target to generate assembly for a file
src/Commands/ClearCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Commands/ClearCommand.cpp.s
.PHONY : src/Commands/ClearCommand.cpp.s

src/Commands/HistoryCommand.o: src/Commands/HistoryCommand.cpp.o
.PHONY : src/Commands/HistoryCommand.o

# target to build an object file
src/Commands/HistoryCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Commands/HistoryCommand.cpp.o
.PHONY : src/Commands/HistoryCommand.cpp.o

src/Commands/HistoryCommand.i: src/Commands/HistoryCommand.cpp.i
.PHONY : src/Commands/HistoryCommand.i

# target to preprocess a source file
src/Commands/HistoryCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Commands/HistoryCommand.cpp.i
.PHONY : src/Commands/HistoryCommand.cpp.i

src/Commands/HistoryCommand.s: src/Commands/HistoryCommand.cpp.s
.PHONY : src/Commands/HistoryCommand.s

# target to generate assembly for a file
src/Commands/HistoryCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Commands/HistoryCommand.cpp.s
.PHONY : src/Commands/HistoryCommand.cpp.s

src/Main.o: src/Main.cpp.o
.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i
.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s
.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/Shell.o: src/Shell.cpp.o
.PHONY : src/Shell.o

# target to build an object file
src/Shell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Shell.cpp.o
.PHONY : src/Shell.cpp.o

src/Shell.i: src/Shell.cpp.i
.PHONY : src/Shell.i

# target to preprocess a source file
src/Shell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Shell.cpp.i
.PHONY : src/Shell.cpp.i

src/Shell.s: src/Shell.cpp.s
.PHONY : src/Shell.s

# target to generate assembly for a file
src/Shell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/src/Shell.cpp.s
.PHONY : src/Shell.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Main"
	@echo "... combined"
	@echo "... emasearch"
	@echo "... factorize"
	@echo "... src/Bench/EmaSearchStrBenchmark.o"
	@echo "... src/Bench/EmaSearchStrBenchmark.i"
	@echo "... src/Bench/EmaSearchStrBenchmark.s"
	@echo "... src/Bench/FactorizeBenchmark.o"
	@echo "... src/Bench/FactorizeBenchmark.i"
	@echo "... src/Bench/FactorizeBenchmark.s"
	@echo "... src/Bench/combined.o"
	@echo "... src/Bench/combined.i"
	@echo "... src/Bench/combined.s"
	@echo "... src/Bench/emasearch.o"
	@echo "... src/Bench/emasearch.i"
	@echo "... src/Bench/emasearch.s"
	@echo "... src/Bench/factorize.o"
	@echo "... src/Bench/factorize.i"
	@echo "... src/Bench/factorize.s"
	@echo "... src/Commands/CdCommand.o"
	@echo "... src/Commands/CdCommand.i"
	@echo "... src/Commands/CdCommand.s"
	@echo "... src/Commands/ClearCommand.o"
	@echo "... src/Commands/ClearCommand.i"
	@echo "... src/Commands/ClearCommand.s"
	@echo "... src/Commands/HistoryCommand.o"
	@echo "... src/Commands/HistoryCommand.i"
	@echo "... src/Commands/HistoryCommand.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/Shell.o"
	@echo "... src/Shell.i"
	@echo "... src/Shell.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

